### ISSUE TITLE
Developer's Guide, error trying to build emsdk on Ubuntu 16.04

### ISSUE THREAD

**Issue by felipellrocha** [WebAssembly/website#103]
I'm trying to follow the web assembly Developer's Guide to install the emsdk. It all compiles fine on OSX, but I'm running into the following error when I'm trying to build it on Ubuntu 16.04:

```
[ 94%] Built target llvm-lto2
[ 94%] Built target llvm-diff
[ 94%] Linking CXX executable ../../bin/llvm-c-test
collect2: error: ld returned 1 exit status
tools/llvm-c-test/CMakeFiles/llvm-c-test.dir/build.make:425: recipe for target 'bin/llvm-c-test' failed
make[2]: *** [bin/llvm-c-test] Error 1
CMakeFiles/Makefile2:15474: recipe for target 'tools/llvm-c-test/CMakeFiles/llvm-c-test.dir/all' failed
make[1]: *** [tools/llvm-c-test/CMakeFiles/llvm-c-test.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Build failed due to exception!
Working directory: /opt/emsdk/clang/fastcomp/build_incoming_64
Command '['make', '-j1']' returned non-zero exit status 2
Installation failed!
```

Does anyone know what is going on?

**Comment by lars-t-hansen** [comment]
I have built the SDK (just now) on Ubuntu 16.04 without problems.

I see the linker uses /lots/ of memory and there are several link jobs running in parallel, my system was up around the 16GB mark during linking.  How much RAM+swap do you have?

**Comment by felipellrocha** [comment]
4gb of memory, 4 gb of swap

**Comment by felipellrocha** [comment]
I just tried upgrading my server to 16gb, 8 cpus, now I'm getting this error:

```
Scanning dependencies of target llvm-dis
[ 88%] Building CXX object tools/llvm-dis/CMakeFiles/llvm-dis.dir/llvm-dis.cpp.o
[ 88%] Linking CXX executable ../../bin/sanstats
[ 88%] Linking CXX executable ../../bin/llvm-cat
[ 88%] Building CXX object tools/yaml2obj/CMakeFiles/yaml2obj.dir/yaml2dwarf.cpp.o
[ 88%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/CodeCoverage.cpp.o
[ 88%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/dwarf2yaml.cpp.o
[ 88%] Linking CXX executable ../../bin/verify-uselistorder
collect2: error: ld returned 1 exit status
tools/sanstats/CMakeFiles/sanstats.dir/build.make:107: recipe for target 'bin/sanstats' failed
make[2]: *** [bin/sanstats] Error 1
CMakeFiles/Makefile2:16284: recipe for target 'tools/sanstats/CMakeFiles/sanstats.dir/all' failed
make[1]: *** [tools/sanstats/CMakeFiles/sanstats.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 88%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/CoverageExporterJson.cpp.o
[ 88%] Building CXX object tools/yaml2obj/CMakeFiles/yaml2obj.dir/yaml2elf.cpp.o
[ 88%] Built target llvm-cat
[ 88%] Building CXX object tools/yaml2obj/CMakeFiles/yaml2obj.dir/yaml2macho.cpp.o
[ 88%] Linking CXX executable ../../bin/llvm-dis
collect2: error: ld returned 1 exit status
tools/verify-uselistorder/CMakeFiles/verify-uselistorder.dir/build.make:110: recipe for target 'bin/verify-uselistorder' failed
make[2]: *** [bin/verify-uselistorder] Error 1
CMakeFiles/Makefile2:15542: recipe for target 'tools/verify-uselistorder/CMakeFiles/verify-uselistorder.dir/all' failed
make[1]: *** [tools/verify-uselistorder/CMakeFiles/verify-uselistorder.dir/all] Error 2
[ 88%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/CoverageFilters.cpp.o
collect2: error: ld returned 1 exit status
tools/llvm-dis/CMakeFiles/llvm-dis.dir/build.make:98: recipe for target 'bin/llvm-dis' failed
make[2]: *** [bin/llvm-dis] Error 1
CMakeFiles/Makefile2:16475: recipe for target 'tools/llvm-dis/CMakeFiles/llvm-dis.dir/all' failed
make[1]: *** [tools/llvm-dis/CMakeFiles/llvm-dis.dir/all] Error 2
[ 88%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/elf2yaml.cpp.o
[ 88%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/CoverageReport.cpp.o
[ 88%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/CoverageSummaryInfo.cpp.o
[ 88%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/macho2yaml.cpp.o
[ 88%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/Error.cpp.o
[ 88%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/SourceCoverageView.cpp.o
[ 88%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/SourceCoverageViewHTML.cpp.o
[ 89%] Linking CXX executable ../../bin/yaml2obj
[ 89%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/SourceCoverageViewText.cpp.o
[ 89%] Built target yaml2obj
[ 89%] Building CXX object tools/llvm-cov/CMakeFiles/llvm-cov.dir/TestingSupport.cpp.o
[ 90%] Linking CXX executable ../../bin/llvm-cov
collect2: error: ld returned 1 exit status
tools/llvm-cov/CMakeFiles/llvm-cov.dir/build.make:366: recipe for target 'bin/llvm-cov' failed
make[2]: *** [bin/llvm-cov] Error 1
CMakeFiles/Makefile2:15982: recipe for target 'tools/llvm-cov/CMakeFiles/llvm-cov.dir/all' failed
make[1]: *** [tools/llvm-cov/CMakeFiles/llvm-cov.dir/all] Error 2
[ 90%] Linking CXX executable ../../bin/obj2yaml
collect2: error: ld returned 1 exit status
tools/obj2yaml/CMakeFiles/obj2yaml.dir/build.make:234: recipe for target 'bin/obj2yaml' failed
make[2]: *** [bin/obj2yaml] Error 1
CMakeFiles/Makefile2:16078: recipe for target 'tools/obj2yaml/CMakeFiles/obj2yaml.dir/all' failed
make[1]: *** [tools/obj2yaml/CMakeFiles/obj2yaml.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
Build failed due to exception!
Working directory: /opt/emsdk/clang/fastcomp/build_incoming_64
Command '['make', '-j7']' returned non-zero exit status 2
Installation failed!
```

**Comment by felipellrocha** [comment]
@lars-t-hansen Anyway you could describe the steps you took to get it compiling correctly? Maybe I have the wrong version of cmake, and gcc installed

**Comment by lars-t-hansen** [comment]
Curious.  I followed the instructions for "Compiling Emscripten from source" on http://webassembly.org/getting-started/developers-guide/ literally, except that I already had emsdk installed, so I did step 2 (cd to emsdk directory) before step 1, which then became `git pull` instead of `git clone`.  It's a number of weeks since the last time I did this, so recompiling did perform quite a bit of work, though nothing like a fresh install.
```
$ cmake --version
cmake version 3.5.1
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.26.1
```
I suggest you try `./emsdk install -j1 ...` just to see if it helps to compile with a single process, because the linker failures you report still look like out-of-memory conditions to me.

@juj, @kripken - have you seen this problem before?

**Comment by juj** [comment]
According to https://stackoverflow.com/questions/27272525/what-does-collect2-error-ld-returned-1-exit-status-mean, `collect2: error: ld returned 1 exit status` suggests an error occurred earlier. Try installing with `-j1` like Lars mentioned, perhaps that will show another error. Also, if you have a temporary build artifacts directory from previous setup, try deleting `$emsdk/clang/fastcomp/build_*` directories that contain the build artifacts. You can also go into that directory after a failed `emsdk install` and manually invoke `make VERBOSE=1` to do a more noisy incremental singlethreaded build from where the earlier failed build attempt left off. Perhaps that might be able to show an issue.

`ld` is known to require lots of memory and fail on virtual machines. You can try setting an environment variable `export LLVM_CMAKE_ARGS="-DLLVM_USE_LINKER=gold"` before doing `emsdk install` to use the `gold` linker if you have it installed. That has been reported to use less RAM.

See also https://github.com/kripken/emscripten/issues/4667.

**Comment by felipellrocha** [comment]
Looks like building for release did it. I was monitoring memory while it built, and it was an insane amount lower than normal.

Thanks, y'all!

**Comment by RobertoMalatesta** [comment]
@felipellrocha last time I tried to build emscripten + wasm on a Linux Machine with 4Gb of RAM I had to set up a temporary swap file (something I did not do since good old Slackware days)
It's something like:

```
As root:
1. dd if=/dev/zero of=tmp_swap bs=<blocksize> count=<howmanyblocksyouwant>
 2. chmod 600 tmp_swap
 3. mkswap tmp_swap
 4. swapon tmp_swap
<compile and do all the dirty things>
then you can delete it with:
 1. swapoff tmp_swap
 2. rm tmp_swap
```

do not take it verbatim since it was some months ago.

Oh, and -j1 is still *essential* nevertheless.

Hth.

--R

**Comment by felipellrocha** [comment]
@RobertoMalatesta Hey. I had tried that already with no success. It helped the build go from stopping at 64% to stopping at 98%, but that was it. Building it for release did it.

**Comment by RobertoMalatesta** [comment]
> t helped the build go from stopping at 64% to stopping at 98%

@felipellrocha 98% ?  it was almost done :P 

Now I remember that during the compilation I monitored the mem usage and added several swapfiles as it showed to be lagging (ended up with a 20Gb total of swap files).
It was *painful* for the machine and for me but now I won't recompile it until wasm threads and shared memory are in. Besides good old emscripten asm.js still does the work pretty well.

BTW: Did you try using gold as @juj suggests?

--R

**Comment by felipellrocha** [comment]
Oh, actually, yes! I also did that!

**Comment by nagu0011** [comment]
[ 53%] Linking CXX executable ../bin/KafkaImporter
[ 54%] Built target Chunk
[ 54%] Built target Calcite
[ 56%] Built target Catalog
[ 57%] Built target Analyzer
[ 57%] Built target CsvImport
[ 58%] Built target QueryRunner
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_verify_mode@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_verify@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_num_locks@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_wbio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_peek@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_destroy_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_use_certificate_chain_file@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_shutdown@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_get_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_locking_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_method@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_load_error_strings@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_get_entry@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_write@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `EVP_cleanup@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_verify_cert_error_string@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_length@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_use_PrivateKey_file@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_peek_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_free_strings@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_num@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_accept@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_remove_state@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ASN1_STRING_to_UTF8@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_clear_error@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_2_method@OPENSSL_1.0.1'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_rbio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_set_fd@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_cleanup_all_ex_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_s_mem@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_read@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_set_bio@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `GENERAL_NAME_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `ERR_reason_error_string@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_connect@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_get_index_by_NID@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_ctrl@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `RAND_poll@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_default_passwd_cb@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSLv23_method@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `BIO_new@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_library_init@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_get_subject_name@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_CTX_set_cipher_list@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_get_ext_d2i@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `X509_NAME_ENTRY_get_data@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `TLSv1_1_method@OPENSSL_1.0.1'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_value@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_create_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `sk_pop_free@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `CRYPTO_set_dynlock_lock_callback@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_verify_result@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_shutdown@OPENSSL_1.0.0'
/usr/local/mapd-deps/lib/libthrift.so: undefined reference to `SSL_get_peer_certificate@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
Import/CMakeFiles/KafkaImporter.dir/build.make:108: recipe for target 'bin/KafkaImporter' failed
make[2]: *** [bin/KafkaImporter] Error 1
CMakeFiles/Makefile2:1354: recipe for target 'Import/CMakeFiles/KafkaImporter.dir/all' failed
make[1]: *** [Import/CMakeFiles/KafkaImporter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- Configuring done
-- Generating done
-- Build files have been written to: /home/thickstat/Downloads/mapd-core/build
[ 58%] Built target rerun_cmake
[ 84%] Built target QueryEngine
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
