### ISSUE TITLE
no native wasm support detected

### ISSUE THREAD

**Issue by ygong10** [WebAssembly/website#105]
I'm using Ubuntu 16.04 on a Virtualbox VM.

After following the developer guide and opening localhost via Google Chrome, I was met with `no native wasm support detected` error in the Javascript console. Then in my terminal, it said to recompile with --emrun linker flag, so I did that, but the error persists.

**Comment by kripken** [comment]
What version of chrome is it? Maybe it's too old to have wasm support.

**Comment by ygong10** [comment]
Ah, I thought I updated my chrome to the latest version, but apparently it wasn't updated (Ubuntu software center bug), so I was still using version 53...

It works now. Thanks!
