### ISSUE TITLE
Some problems with running EpicZenGarden demo locally

### ISSUE THREAD

**Issue by ZhangQP** [WebAssembly/website#106]
@juj 
Hello, in https://github.com/WebAssembly/website/issues/86, some demos are mentioned and ZenGarden is strongly recommended, so I tries to download and run it locally. I have tried two ways, one is the emrun.py and the other is Apache Server. The former one works successfully and fast. However, with Apache Server, the first probelm is 
![1](https://user-images.githubusercontent.com/8079681/30379330-b5d63602-98c8-11e7-98e0-ea94c4c5ccaf.png)
I solved this with "Unzip all foo.bar.gz files"  and "change const serveCompressedAssets = true; to const serveCompressedAssets = false;" just as mentioned in issue 86. Then it works in Chrome, with another problem
![2](https://user-images.githubusercontent.com/8079681/30379443-1747a416-98c9-11e7-9a83-a9e29ed41ef8.jpg)
what does this mean? There is nothing in IndexedDB? or all the unziped files and data are saved in IndexedDB just the same as we visit https://s3.amazonaws.com/mozilla-games/ZenGarden/EpicZenGarden.html directly, but WASMmodule cannot be read?
In addition, I have another two questions:
1. Can I consider the emrun.py as a local server just as Apache? Is there any difference?
2. I mentioned that the two local methods takes much less time than visiting the website online directly, except for the effect of Internet, are there any other reasons? Especially, it seems that emrun.py takes little time to compile WebAssembly, it's the fact with some reasons or just my illusion?
Thank you!

**Comment by juj** [comment]
> what does this mean?

Unless there is some problem with the error detection on the page (might be, the error cases were not simulated too hard), I read this to mean that the browser does not have IndexedDB support at all available. Alternatively, this could mean that the browser does not support caching compiled WebAssembly Modules to IndexedDB.

> Can I consider the emrun.py as a local server just as Apache? Is there any difference?

`emrun.py` is based on `python -m SimpleHTTPServer`, but it enables gzip compression. Articles such as https://stackoverflow.com/questions/5693741/whats-difference-between-a-simple-webserver-and-apache-server are probably better at explaining differences between Python web server and Apache.

> except for the effect of Internet, are there any other reasons?

There should not be. With the exception that the bits are flowing much slower from the internet, all initialization steps are identical. What does happen though is that WebAssembly compilation and shader compilation will happen parallel to downloading other assets, so running on the web may make it seem as if one only had to wait for the download and not much else.

> Especially, it seems that emrun.py takes little time to compile WebAssembly, it's the fact with some reasons or just my illusion?

With both emrun.py and a public web server, WebAssembly compilation step should be the same. The intended mode is that all downloads and WebAssembly Module compilation get cached to IndexedDB, so second page run should be really fast, and dominated by the time it takes to compile shaders.

What might be different with local vs public CDN is if for some reason browser caching of WebAssembly or assets is not working with localhost. The `wasmModule` related error might be in play here.

If you run the page in benchmark mode, with `?playback&novsync` GET params, e.g.

https://s3.amazonaws.com/mozilla-games/ZenGarden/EpicZenGarden.html?playback&novsync

you will get timing information about the different steps printed on the web page at the very end. That can help diagnose loading times.

**Comment by RobertoMalatesta** [comment]
>  I read this to mean that the browser does not have IndexedDB support at all available

If you are using Firefox and you're switching from -say- version 57 to a previous one like 54, IndexedDB can become unavailable due to format version incompatibilities.

@ZhangQP : you should have an error (more than one) reported in the console about that.

--R

**Comment by ZhangQP** [comment]
@juj I switch from Chrome to Firefox, and the IndexedDB problem disappears. It seems that browser is indeed the main reason. Thank you for you help!

**Comment by binji** [comment]
This is a pretty old bug, and issue seems to be resolved. Reopen if not.
