### ISSUE TITLE
Broken link on Future Features

### ISSUE THREAD

**Issue by b0x1** [WebAssembly/website#108]
The link http://webassembly.org/docs/gc/ in section GC/DOM Integration is broken on http://webassembly.org/docs/future-features/ .

**Comment by thomasnat1** [comment]
Looks like this was due to a commit where @jfbastien removed it from the [design repo](https://github.com/WebAssembly/design/tree/9a6d9d59ff4245ffced4b8257f773dbedc5112ff). 
@jfbastien, is there a replacement doc that we should link to or should we just remove this section from the website for now?

**Comment by jfbastien** [comment]
This was fixed here: https://github.com/WebAssembly/design/commit/27ac254c854994103c24834a994be16f74f54186

But @flagxor needs to push recent changes to web assembly.org

**Comment by thomasnat1** [comment]
Got it, I will push the changes

**Comment by thomasnat1** [comment]
Pulled latest version of design docs and pushed them to site
