### ISSUE TITLE
Docs link from Getting Started page is broken

### ISSUE THREAD

**Issue by tbodt** [WebAssembly/website#125]
The HTML generated for that link is `<a class="site-nav-item btn" href="">Docs</a>`, which just reloads the current page. All other pages I've looked at have this link correct.

**Comment by nidin** [comment]
Specifically, Not able to navigate from page `https://webassembly.org/getting-started/developers-guide/ ` to (Docs) `https://webassembly.org/docs/high-level-goals/`

**Comment by binji** [comment]
This seems to be fixed now.
