### ISSUE TITLE
No audio the first 10-15 seconds in chrome

### ISSUE THREAD

**Issue by binoculars88** [WebAssembly/website#126]
In chrome, the audio seems to start too late in the Tanks demo.
You can already play the game, and then, after 10-15 seconds, the audio pops on.
Everything is working fine in Firefox.

What can be the cause of this? The reason I ask is because I experience the exact same bug with my Unity WebGL wasm game... it used to work but now all of the sudden this audio bug appeared (maybe after an automated chrome update?)

**Comment by binji** [comment]
Closing since the demo is now removed.
