### ISSUE TITLE
Potential error in the headline of the main page

### ISSUE THREAD

**Issue by Ellinn** [WebAssembly/website#138]
Headline of the [main page](https://webassembly.org/) says

> WebAssembly (abbreviated Wasm) is a binary instruction format for a stack-based virtual machine. Wasm is designed as a portable target for compilation of high-level languages like C/C++/Rust, enabling deployment on the web for client and server applications.

Aren't C/C++/Rust [low-level programming language](https://en.wikipedia.org/wiki/Low-level_programming_language) ?

**Comment by binji** [comment]
No, I don't think they are low-level programming languages. The link you provide says similar:

> Low-level languages can convert to machine code without a compiler or interpreter

> By comparison, a high-level programming language isolates execution semantics of a computer architecture from the specification of the program,

By this definition at least, those languages are all high-level.

**Comment by rossberg** [comment]
> Low-level languages can convert to machine code without a compiler or interpreter

That Wikipedia page equates low-level language with assembly language, which sounds less than useful or common. (Of course, some claim that even C is just a glorified macro assembler...)

I don't think there is a clear-cut definition for these terms, and low vs high-level is rather a relative notion (with high-level being very much open-ended). But I am acquainted to low-level languages referring to those that give you raw access to hardware resources like memory, pointers (memory addresses), endianness, and other native notions, or require/allow explicit management of these resources. That would certainly include C/C++.

You can always cop out by saying "lower-level"/"higher-level", thereby emphasising the relative nature of the terms.

**Comment by Ellinn** [comment]
@rossberg Thanks for this complete point of vue. This is a pretty ambiguous subject.

I thought that high-level languages were languages like Python, Ruby, etc and considering C, C++, etc more like low-level languages because of the raw access to hardware resources like you said.

But I guess the fact is just things like machine or assembly languages are the real low-level programming languages.
