### ISSUE TITLE
The Module Start Function documentation is unintelligible

### ISSUE THREAD

**Issue by carlsmith** [WebAssembly/website#147]
Within [the *Imports* section of the *Modules* documentation][1], there is a section named *Module start function* that begins like this:

> If the module has a start node defined, the function it refers should be called by the loader after the instance is initialized, including its Memory and Table though Data and Element sections, and before the exported functions are callable.

Trying to figure out what was meant, the best I can do is this:

> If a module defines a start function (roughly analogous to the `main` function in a C program), that function should be called by the loader after the instance is initialized (which must include initialization of any linear memories or tables imported by the module, though Data and Element sections are different, somehow). If a start function is defined by a module, any functions exported by that module will not be callable (anywhere) until after the start function has been called.

I'd be grateful for any help with understanding how the start function works, but the actual issue is obviously that the docs need editing.

[1]: https://webassembly.org/docs/modules/#imports

**Comment by carlsmith** [comment]
There are other issue with the section, which make it difficult to work around the problems with the introductory paragraph. For example, there are two bullet points (one in the first list and one in the second) that seem to contradict each other (my emphasis):

+ The function is identified by function index, *can be an import*, and can also be exported
+ If a module contains a start node, the function *must be defined in the module*

Aside from the fact that the top point is at least two points, and probably three, the statement that the start function can be an import conflicts with the statement that it must be defined in the module.

**Comment by carlsmith** [comment]
The last bullet point from the second list says:

> The start function will be called after module loading and before any call to the module function is done

What does *the module function* refer to?

Just to be clear, I've so far found the rest of the document to be well written and very useful, but the *Module start function* section badly needs editing.

**Comment by lukewagner** [comment]
Modules.md is very old, and predates the writing of the [real specification](https://webassembly.github.io/spec/core/index.html).  Maybe we should just delete it?

For reference, although it may be a hard to jump in without a bit of context, here's the [start function validation rule](https://webassembly.github.io/spec/core/valid/modules.html#start-function) and the execution rule is [step 15 inside the instantiation execution rule](https://webassembly.github.io/spec/core/exec/modules.html#instantiation).

**Comment by carlsmith** [comment]
Thanks @lukewagner.

I would strongly prefer the document to stay up for the time being, maybe with a warning about it being dated and unmaintained. I'm learning to write WAT by hand (just to understand it better), and the rest of that document has been very useful to me.

The specs are (as required) written in a style that makes them difficult to use as a starting point, and tutorials tend to skip over a lot of important details, but that document has the perfect level of detail to bridge the gap, and there isn't much else like that online yet.

**Comment by carlsmith** [comment]
I'm really struggling to decipher important parts of the spec, and hoped somebody could clarify a few things:

+ Can the start function be an import?
+ Can the start function be exported?
+ What (potentially) needs initializing by the host prior to calling a start function?

Thanks for your patience.

**Comment by lukewagner** [comment]
Thanks for the feedback and glad to hear there is a use case for these documents.  To answer your questions:
* Yes, the start function can be an import (the start function is specified by a function index and all functions, imports and internal definitions, go into the function index space)
* Yes, any function (import or locally-defined) can be exported; whether it is *also* used as a start function is simply an orthogonal choice from whether it is exported
* The wasm spec specifies that, after the instance is created, data and elem segments are written into memories and tables, resp., before the start function is executed

(If you have any time and would like to contribute, feel free to contribute a clarifying PR to Modules.md that would've answered these questions for you.)

**Comment by carlsmith** [comment]
Thank you, @lukewagner - much appreciated.

> (If you have any time and would like to contribute, feel free to contribute a clarifying PR to Modules.md that would've answered these questions for you.)

:) No problem. I'd be happy to.

I'll edit the *Start Function* section soon, and try and catch any other obvious fixes (`get_global` to `global.get`) while I'm doing that, then look at overhauling the rest of the document later on. There isn't much wrong with the other sections.

Thanks again.

**Comment by carlsmith** [comment]
@lukewagner - I edited the Modules doc, and have pushed the commit to [my fork][1], but it's getting really late here, so I'll go over it and create a PR once I've had some sleep.

[1]: https://github.com/carlsmith/website/blob/master/docs/design/Modules.md
