### ISSUE TITLE
A subdomain for the WebAssembly Summit

### ISSUE THREAD

**Issue by RReverser** [WebAssembly/website#152]
Hi all!

Google and Mozilla are organising a WebAssembly Summit on February 10th, 2020.

We'd like to get a `summit2020.webassembly.org` subdomain as a landing page for this event (general info, user registration, etc.).

Who could advise on the process for getting such subdomain? (Ideally we'd like to do this as quickly as possible as there is not too much time to the event, especially considering holidays in between.)

Thanks! /cc @surma @linclark

**Comment by linclark** [comment]
I wonder if it might make sense to do `summit.webassembly.org/2020/`?

I don't yet know how to register a webassembly.org subdomain, but I'm asking around.

**Comment by natorion** [comment]
I think @lukewagner should have the power.

**Comment by surma** [comment]
@linclark I went back and forth on that myself. I don’t have strong opinions either way.

The only reason I prefer `summit2020.webassembly.org` is because it would allow us to keep the old sites online if and when the next summit comes. We might want to use a completely different hoster / tech stack for future sites and these would keep them separated. With `/2020/` we’d need some sort of reverse proxy.

**Comment by ttraenkler** [comment]
summit.webassembly.org/2020/* could redirect to the old site in that case, no matter what the tech stack of the new site. this way we don't have to setup a new subdomain each year which might delay the announcement.

**Comment by RReverser** [comment]
Ping @lukewagner.

**Comment by linclark** [comment]
Luke and I have discussed this and I'll be taking it on.

It seems like there's still some uncertainty about whether to use `summit` or `summit2020` given the comment directly above, though. Once that's resolved, I can put in the request.

**Comment by surma** [comment]
let's do `summit.webassembly.org`

**Comment by linclark** [comment]
Ok, I'll go ahead and put in the request.

**Comment by linclark** [comment]
It turns out the IT person who manages this is out this week. I expect it will be resolved pretty quickly on his return next week, and will follow up if it isn't.

**Comment by RReverser** [comment]
Closing as obsolete now.
