### ISSUE TITLE
Roadmap checkmarks are ambiguous

### ISSUE THREAD

**Issue by kripken** [WebAssembly/website#171]
"JS BigInt to Wasm i64 integration" has a checkmark for wasmtime and wasmer, which I guess means "all necessary support is present", that is, they have no JS, so no support is needed, so it's implemented there "in the empty sense". Is that right?

This does make sense in that someone looking at the *row* for "JS BigInt to Wasm i64 integration" probably wants to see a checkmark there, if they are curious if they can ship with that feature.

However, it is ambiguous and it confused me. In particular, when looking at the *column* for a JS-less VM and wondering what has been implemented there, it gives the wrong answer.

Perhaps there could be a non-ambiguous symbol for "irrelevant" or "unnecessary"? I don't have a great idea, but maybe a green checkmark for "implemented" and a gray checkmark for "irrelevant"? Or if color isn't enough, a circle for "irrelevant"? (which is clearly neither a checkmark, an X, or an hourglass)

**Comment by kripken** [comment]
@RReverser ping on this - every time I view the graph, this confuses me, so I'm betting it confuses other people too...

A gray circle (with alt-text "N/A") seems like it could work here? Happy to try to make a PR if there's agreement. (Although not sure my webdev skills are good enough...)

**Comment by RReverser** [comment]
> I don't have a great idea, but maybe a green checkmark for "implemented" and a gray checkmark for "irrelevant"?

I don't really control colour there - it's just part of the Unicode font emoji image. There might be some way to change its hue, but no way to set color directly. I suspect using some different symbol might be preferable.

In general, the checkmark just means that the engine passed the wasm-feature-detect tests, which for non-JS engines indeed means just "compiles the Wasm" part. When the feature is JS-specific, like in case with BigInt, then yeah, it can lead to confusion.

**Comment by kripken** [comment]
I see, thanks... ok, I opened a PR now, let me know what you think.
