### ISSUE TITLE
Update Microsoft Edge logo on home page

### ISSUE THREAD

**Issue by alvinashcraft** [WebAssembly/website#231]
The Edge logo on the home page is the old "E" logo used by the non-Chromium based Edge. This should be updated to use the new logo. [https://en.wikipedia.org/wiki/Microsoft_Edge#/media/File:Microsoft_Edge_logo_(2019).svg](url)

**Comment by sidverma32** [comment]
Hi @alvinashcraft  , Shall i pick this up ? As this will be my first contribution to the repo.

**Comment by alvinashcraft** [comment]
Yes, this one sounds like a great first contribution, if you are interested.

**Comment by chicoxyzzy** [comment]
Fixed in https://github.com/WebAssembly/website/pull/283/commits/fb84f2abd4525371ff70c7609d8bff4fb358eaf1#diff-f12839dc24ee04589e18aec3114fc2c2727da5b3e219a8c42cac7cbce18d4200
