### ISSUE TITLE
Add use from Python

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [WebAssembly/website#238]
I cannot see use from Python on the website, Python has this package:

https://github.com/wasmerio/wasmer-python

which enables calling wasm files.

**Comment by AestheticOwl** [comment]
Bumping thread for above reason

**Comment by purplelemons-dev** [comment]
bump more than a year later. still not on site.

**Comment by dschuff** [comment]
I'm adding it, but note that the list of languages is a list of languages that are compiled to/implemented on top of wasm, not a list of wasm embeddings *into* the languages. There isn't a list of those, and I wouldn't want to create one with only Wasmer/Python in it. If someone wanted that, I think they should collect a much more comprehensive list and add it all at once.
