### ISSUE TITLE
Report a broken URL link

### ISSUE THREAD

**Issue by abdelrazek-alaa** [WebAssembly/website#253]
Hello, I'd like to report a broken URL link.

Broken link : 
https://webassembly.org/docs/dynamic-linking

Specific section or headline:
Getting started - JS API page
The last line on the JS API page.
>They allow a single Memory object to be imported by multiple instances, which is a critical building block for implementing [dynamic linking](https://webassembly.org/docs/dynamic-linking) in WebAssembly.

**Comment by RReverser** [comment]
Thanks for the report. Fixed / added a redirect to the proposal document.
