### ISSUE TITLE
roadmap still updated?

### ISSUE THREAD

**Issue by tijmenvangulik** [WebAssembly/website#281]
Is the roadmap still updated? I use this page to see the progress. Some issue:

* The module linking leads no no where. It looks like that module linking activity moved to the component model (source: https://github.com/WebAssembly/module-linking)
* extended constant expressions is only marked as in progress for firefox but when I look at the website of the proposal implementations are also ready for v8, source:
https://github.com/WebAssembly/extended-const/blob/master/proposals/extended-const/Overview.md

**Comment by RReverser** [comment]
This should be resolved.
