### ISSUE TITLE
Update default branch name of `main`

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/website#287]
This seems to have been done on all the other repos but not this one for some reason.

**Comment by RReverser** [comment]
Note: care will need to be taken to update GH actions too. https://github.com/WebAssembly/website/blob/f71874340018540fd0bae110da4c5225ec4168e7/.github/workflows/deploy.yml#L3-L7

**Comment by sbc100** [comment]
I wonder if we could also make "squash and merge" the default for this repo to avoid all those extra merge commits?

**Comment by andylizi** [comment]
> Note: care will need to be taken to update GH actions too.

With #302 merged this can be closed now.
