### ISSUE TITLE
https for webasssembly.org

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/website#30]
Follow-up from #20, webassembly.org should support https, ideally with HSTS and HSTS preload.
/cc @lgarron

**Comment by jfbastien** [comment]
At the moment github doesn't support https on github pages with a custom domain: https://help.github.com/articles/securing-your-github-pages-site-with-https/

When I go here: https://github.com/WebAssembly/webassembly.github.io/settings
I see:

>    *Enforce HTTPS* — Unavailable for your site because you have a custom domain configured ([webassembly.org](webassembly.org)) 
>    HTTPS provides a layer of encryption that prevents others from snooping on or tampering with traffic to your site.
>    When HTTPS is enforced, your site will only be served over HTTPS. [Learn more](https://help.github.com/articles/securing-your-github-pages-site-with-https/).

I think we should instead set up webassembly.org with https, HSTS, HSTS preload, and have it HTTP 302 to webassembly.github.io, which should itself be https-enabled with the checkbox from the above settings page.

Once github pages with custom domains do support https then we can reverse the redirect direction, use 301 instead. At no point would we serve without https if we follow this.

**Comment by s3ththompson** [comment]
I agree HTTPS is a high priority. Given the fact that we will eventually want a real custom domain name & HTTPS, should we just start considering moving off of GitHub pages for hosting? It is unlikely that GitHub pages will offer true HTTPS given the need to verify identity at the origin level...

**Comment by jfbastien** [comment]
@s3ththompson good point. webassembly.org could be a deep mirror of the github page?

**Comment by s3ththompson** [comment]
By deep mirror do you just mean that we set up the hosting to automatically mirror whatever's hosted on GitHub?

**Comment by jfbastien** [comment]
> By deep mirror do you just mean that we set up the hosting to automatically mirror whatever's hosted on GitHub?

Yup. Or we do a standalone thing, doesn't really matter. It is nice to manager a site through github, and I don't see a reason why we wouldn't want it to be fully static so it should be pretty straightforward.

**Comment by s3ththompson** [comment]
Agreed. That sounds like a good idea.

**Comment by henricavalcante** [comment]
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by annevk** [comment]
I noticed this is still an issue. FWIW, for WHATWG standards, and also whatwg.org itself, we use a simple deploy script that Travis runs and copies files over through rsync: https://github.com/whatwg/whatwg.org/blob/master/deploy.sh.

**Comment by distransient** [comment]
I wouldn't recommend putting webassemby.org behind a cloudflare proxy for accessibility reasons. @annevk's linked script seems nice!

**Comment by raviqqe** [comment]
How about interleaving some kind of CDN like AWS CloudFront? I do that for my website.

**Comment by Nektro** [comment]
[Netlify](https://www.netlify.com/) has free SSL, Custom Domains, forced HTTPS, and integrates seamlessly with GitHub projects

**Comment by macsual** [comment]
[Custom domains on GitHub Pages gain support for HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)

**Comment by lukewagner** [comment]
\o/  I think we're using an A record so I'll put in a request to have the necessary changes made.

**Comment by macsual** [comment]
It is using an A record so that's all you have to do. The A record just needs to be updated to point to GitHub's new IP addresses. Great!

**Comment by lukewagner** [comment]
[Done](https://webassembly.org)

**Comment by annevk** [comment]
Since there's no redirect or HSTS you probably want to update the link at https://github.com/WebAssembly/website and various other places. And maybe ask GitHub about a redirect and HSTS...

**Comment by macsual** [comment]
Yay!  But ["HTTPS enforcement"](https://help.github.com/articles/securing-your-github-pages-site-with-https/) should now be enabled so that all HTTP requests to the website will automatically be upgraded to HTTPS.

**Comment by lukewagner** [comment]
I checked the "Enforce HTTPS" checkbox; it's taking a second to update.  Regardless, I updated  https://github.com/WebAssembly/website; I think a number of other http://s were [already updated](https://github.com/WebAssembly/website/pull/117).
