### ISSUE TITLE
Update site architecture

### ISSUE THREAD

**Issue by s3ththompson** [WebAssembly/website#36]
Proposed site architecture. I'll be migrating on the `browser-preview` branch.
- [x] Overview
- [x] Demo, #35, #27 
- [x] Getting Started
  - [x] Introduction
    - Hello World
    - Binary Format / Text Format, #21, #31 
    - JS API, #22 
  - [x] Developer's Guide
    - current Step-by-Step (Emscripten)
  - [x] Advanced
    - non-Emscripten toolchain overview, #23 
- [x] Documentation (link to design repo)
- [x] Community
  - [x] W3C Group
  - [x] Feedback, #24 
  - [x] Contribution
- [x] Roadmap, #25 (document done, will publish in morning)
- [x] FAQ, #26

**Comment by jfbastien** [comment]
Under community, we should probably explain what comes after the W3C group (or should that be in the roadmap?).

**Comment by s3ththompson** [comment]
@jfbastien Agreed. Probably both!

Also, what do you think about moving the FAQ from the design repo to the site? Site seems like a more natural place for it?

(Contribution seems fine to duplicate between repos, esp. since it is shorter and more likely to not change.)

**Comment by jfbastien** [comment]
I liked your idea of mirroring things from the design repo onto the site, that would take care of the FAQ. I think having an FAQ specifically for the design makes sense.
