### ISSUE TITLE
Feature page does not load

### ISSUE THREAD

**Issue by AustinWise** [WebAssembly/website#363]
At the top of the website there is a link titled "Feature Extensions" that links to https://webassembly.org/features/ . Visiting this does a 301 redirect to https://webassembly.org/roadmap/ . https://webassembly.org/roadmap/ returns a 404 error.

Looking at the HTTP headers, I suspect this 301 redirect is being done by Cloudflare (there is no `x-github-request-id` header on the response). Also the word "roadmap" does not exist in this repo.

**Comment by dschuff** [comment]
Yes, this is definitely the result of https://github.com/WebAssembly/website/pull/361
If I don't hear back from @RReverser today I'll just revert that PR to fix, and we can reland it once we fix the redirection.

**Comment by RReverser** [comment]
Should be fixed now.

**Comment by AustinWise** [comment]
Thanks, I can confirm it's working now.
