### ISSUE TITLE
Threads and atomics detection seems to not work

### ISSUE THREAD

**Issue by bludev** [WebAssembly/website#365]
I've noticed recently that the "Threads and atomics" test doesn't work (tested in Chrome 120, Edge 120 and Firefox 121).

![image](https://github.com/WebAssembly/website/assets/15612827/755688c8-5f78-48a5-96c8-772803552269)

**Comment by RReverser** [comment]
Thanks, this was broken in https://github.com/WebAssembly/website/pull/361 as we changed the URL and headers were still matching the old one.

This should be fixed now.
