### ISSUE TITLE
Extended constant expressions is enabled by default in Safari 17.4

### ISSUE THREAD

**Issue by ggallant-dovico** [WebAssembly/website#376]
The [features](https://webassembly.org/features/) page currently lists Extended constant expressions being enabled in Technology Preview 184.

The feature is actually live and enabled by default in Safari 17.4: [https://webkit.org/blog/15063/webkit-features-in-safari-17-4/](https://webkit.org/blog/15063/webkit-features-in-safari-17-4/)

**Comment by dschuff** [comment]
Thanks I had forgotten I opened that PR 😅
