### ISSUE TITLE
Bootstrapping a custom language in WebAssembly?

### ISSUE THREAD

**Issue by metametaphysician** [WebAssembly/website#402]
Chariots!

Please excuse my ignorance, but where do I begin the research process into bootstrapping my language natively in WebAssembly?

I believe WASM to be the future of the browser, the internet, and the larger Milky Way galaxy, so I would prefer to implement my language in WASM as soon as is pedagogically possible.

Thank you!

Cordially,
Metametaphysician

**Comment by metametaphysician** [comment]
Why would you want to do that? Just write it in Rust.

**Comment by dschuff** [comment]
I don't know of a "definitive" guide to creating a language just for WebAssembly. There are a couple of different ways to think about it, and it depends on your goals and your experience.
If you have a backend that targets other architectures (especially if your language isn't garbage-collected), you can consider 
wasm with linear memory pretty similarly to other architectures and share a lot of the code. You can even use Binaryen (https://github.com/WebAssembly/binaryen/) to help you paper over some of the differences (e.g. structured control flow) if you want.
OTOH if you want to learn as much as possible about how wasm is *different* from other targets, then... well, don't do that :)
If you want to get a GC for free, or integrate better with JavaScript, then lean into wasmGC as much as possible. Then maybe you can write that guide for the next generation of language bootstrappers :)

**Comment by metametaphysician** [comment]
Thank you, @dschuff! 🤙🏼

I just received my copy of Brian Sletten's *WebAssembly: The Definitive Guide* in the mail yesterday, but, as expected, it's another Rust bible masquerading as a WebAssembly gospel.

[Aside: I get it. Rust is C##. We know. Go nuts, Rustaceans! Rewrite the world! For my part? Lisp or death.]

To answer your question: I want to learn as much as possible, with as little hand-waving and magic-pixie-dust as possible (I still love you, Binaryen), so I'll just start with a vanilla WebAssembly/WASM/WASI/WAT directory and work my way up through the Lambda Calculus, Lisp 1.5, Scheme & Logoi. If that doesn't work... I'll try something else.

**Comment by tomayac** [comment]
If you consider going the Binaryen route, I've created a [mini tutorial](https://web.dev/articles/binaryen) for how to get started with it with a toy language (calling it "language" is quite a stretch to be honest) I called ExampleScript. 

Other than that, we can close the Issue I think. The discussion can still continue.

**Comment by rossberg** [comment]
As part of the design work for the GC extension, I implemented two prototype compilers that compile directly from source to Wasm:

- [Waml](https://github.com/WebAssembly/gc/blob/waml/proposals/gc/waml/README.md), an OCaml-style FP language 
- [Wob](https://github.com/WebAssembly/gc/blob/waml/proposals/gc/wob/README.md), a C#-style OO language

The code might have bit-rotted slightly by now (I still plan to update it at some point), but it could still give you some useful ideas. In particular, the READMEs give overviews of how source-language constructs are mapped to Wasm GC. There are also [slides](https://github.com/WebAssembly/meetings/blob/fa5141be9bdab2d221b1ae37ec43964b5c98cc12/gc/2021/presentations/2021-11-16-rossberg-wob+waml.pdf) with additional explanations.

**Comment by metametaphysician** [comment]
@rossberg: These links are the *perfect* starting point for my monkey brain. Thank you! 🙏

**Comment by metametaphysician** [comment]
And yes, I'm even crazy enough to attempt a WebAssembly implementation of the Warren Abstract Machine (WAM) so as to have & eat my delicious Prolog cake. 🎂

Somebody please stop me.

**Comment by metametaphysician** [comment]
Update: DTSTTCPW.

WebAssembly can parse V/PP/PN/L directly into WebAssembly modules in exactly the same way that QSS parse English/Esperanto/etc. directly into Prolog.

Progress > Perfection 🤙🏼
