### ISSUE TITLE
Broken link on http://webassembly.org/roadmap/

### ISSUE THREAD

**Issue by basile-henry** [WebAssembly/website#45]
The link for the spec repo is written like this:

```
<a href="github.com/webassembly/spec">spec</a>
```

Which is a link to this non-existent page `http://webassembly.org/roadmap/github.com/webassembly/spec`

Instead like this other links on the page it should be preceded by `http` or `https` (which by the way seems inconsistent for the other links on the page) :

```
<a href="https://github.com/webassembly/spec">spec</a>
```

**Comment by basile-henry** [comment]
Actually it looks like it's been fixed by 936e86fbb01d5744dcee6d125f4a82e19f5c26f2 and isn't live yet, closing the issue.

**Comment by jfbastien** [comment]
@s3ththompson could you look into why it's not live?

**Comment by s3ththompson** [comment]
The fix was committed without building the Jekyll site and committing the `docs` folder. I need to set up a Travis CI script that is green only if `docs` has been updated... more on that soon. I also updated the README to clarify that site needs to be manually built.
