### ISSUE TITLE
Developer's Guide instructions wrong?

### ISSUE THREAD

**Issue by chchrist** [WebAssembly/website#50]
Hello,

After using developer's guide I get 

```
WARNING  root: Assigning a non-existent settings attribute "WASM"
WARNING  root:  - did you mean one of ASM_JS?
WARNING  root:  - perhaps a typo in emcc's  -s X=Y  notation?
WARNING  root:  - (see src/settings.js for valid values)
```

Are these instructions correct?

**Comment by kripken** [comment]
My guess is that somehow you got the wrong version of `emcc`, what does `emcc --version` say?

**Comment by cristianstaicu** [comment]
I get the same error on Ubuntu using emcc 1.36.0. Here is my "emcc --version" output:
emcc (Emscripten gcc/clang-like replacement) 1.36.0 
(commit 07b87426f898d6e9c677db291d9088c839197291)

**Comment by kripken** [comment]
@cristianstaicu: correct, 1.36.0 on the master branch is before that API was updated, so that is expected. Using the incoming branch (1.36.14) should work. But hopefully before the end of this week we'll merge 1.36.14 to master.

**Comment by cristianstaicu** [comment]
But then the "Getting Started" guide at this link is not working: 
http://webassembly.org/getting-started/developers-guide/
,right? Since by following the steps you get version 1.36.0 which does not have the WASM flag/capabilities. Or am I missing something?

**Comment by s3ththompson** [comment]
I believe this is fixed now.
