### ISSUE TITLE
docs/semantics

### ISSUE THREAD

**Issue by qfox** [WebAssembly/website#53]
Comments/formatting of https://github.com/WebAssembly/website/tree/master/docs/docs/semantics

Maybe add a link that explains "sign extending" and one that explains "integer wrapping".

There's `grow_memory` and `current_memory` but no `available_memory`? Or does this page simply not mention it? Because otherwise you'd need a loop to get that information. Somewhere somebody is going to depend on this and since this information can already be gotten through an expensive loop, why not expose an explicit way of getting the remaining available size?

"These restrictions may be relaxed in the [future :unicorn:][types].", (formatting) link doesn't show up.

"thus cannot be arbitrarily aliased as bits.", bits? Does that mean pointers? I may be ignorant of the term in "bits" this context.

"Execution semantics of control instructions", some cases explicitly say "value stack", others just say "stack". Is there a difference? Feels inconsistent.

"abling [full IEEE 754-2008 support :unicorn:][future ieee 745].", (formatting) link not showing up.

"neg, abs, or copysign is a NaN", (formatting) the nan could be backticked as well, also occurs in various other places in the document. It just stood out to me in this sentence.

**Comment by s3ththompson** [comment]
Thanks for reading the site closely and opening this issue!

The source for the website `docs/` section is actually the [design repo](https://github.com/WebAssembly/design). I've created a [PR](https://github.com/WebAssembly/design/pull/865) to fix the link formatting issues.

Please open an issue on the design repo to discuss the other details and clarifications.
