### ISSUE TITLE
Cant compile Hello World example on macOS Sierra

### ISSUE THREAD

**Issue by Nithanaroy** [WebAssembly/website#54]
Followed all instructions devotedly given on http://webassembly.org/getting-started/developers-guide/
Could not compile hello.c as mentioned.
[error.log.zip](https://github.com/WebAssembly/website/files/590947/error.log.zip)

**Comment by kripken** [comment]
Looks like https://github.com/WebAssembly/binaryen/issues/822.

**Comment by Nithanaroy** [comment]
I was able to run the demo hello world program following the steps from [https://gitlab.sd.apple.com/npasumarthy/my-first-webassembly]()
[README.pdf](https://github.com/WebAssembly/website/files/591246/README.pdf)

**Comment by s3ththompson** [comment]
Closed by https://github.com/kripken/emscripten/pull/4734
