### ISSUE TITLE
/demo/AngryBots/Release/AngryBots.mem is not found

### ISSUE THREAD

**Issue by starkwang** [WebAssembly/website#60]
This file is not found in repo, which makes http://webassembly.org/demo/AngryBots/ unavailable

**Comment by s3ththompson** [comment]
`UnityLoader.js` should fall back to `AngryBots.memgz` when it can't find `AngryBots.mem`.

If http://webassembly.org/demo/AngryBots/ is unavailable for you, please provide more information to reproduce the issue.

**Comment by melkir** [comment]
Same here I got 404 not found
http://webassembly.org/demo/AngryBots/Release/AngryBots.mem

**Comment by s3ththompson** [comment]
As noted above, this error is working as intended. The `UnityLoader.js` should fall back to `AngryBots.memgz` instead.

**Comment by anicholson** [comment]
@s3ththompson well it's not.

**Comment by s3ththompson** [comment]
We have updated benchmarks. The new Unity demo has a different file structure.
