### ISSUE TITLE
: wasm validation error: at offset 8: binary version 0x1 does not match expected version 0xd  index.html:31:24          

### ISSUE THREAD

**Issue by Jiang-Xuan** [WebAssembly/website#79]
Sorry, if I put question in wrong place😬.
When i compile C code to wasm.
I used emcc.
I get this error information in firefox javascript console.
```js
: wasm validation error: at offset 8: binary version 0x1 does not match expected version 0xd  index.html:31:24          
```
I don't know what case this error.
Can you help me, please?

I am China boy is not good at english, please don't keep in mind if i said something wrong.

**Comment by jfbastien** [comment]
> I am China boy is not good at english, please don't keep in mind if i said something wrong.

Your language is perfectly fine, no need to apologize! Many of us are also non-native English speakers 😄 

I believe the problem you're running into is that WebAssembly [is moving to version 1](https://lists.w3.org/Archives/Public/public-webassembly/2017Feb/0002.html). Older toolchains and browsers expected version `0xD` as a pre-release thing. They now expect version `0x1`.

You're therefore hitting the transition period between pre-release and initial-release. Your browser is ahead of the toolchain you're using.

Can you specify which browser version you're using, and which toolchain version you're using?

The problem will resolve itself as everything gets updated to the released version. This is an unfortunate side-effect of the initial release.

**Comment by Jiang-Xuan** [comment]
Firefox Developer Edition: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:52.0) Gecko/20100101 Firefox/52.0

emcc -v: 

```
jiangxuandeMacBook-Pro:hello7 jiangxuan 🍇
$emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.3
clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 5725e3dd8325570ac9d92924fb1af5db9e879e58) (https://github.com/kripken/emscripten-fastcomp/ 9735be7b8bee9c207f33244fe3c5f85f45094470) (emscripten 1.37.3 : 1.37.3)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Users/jiangxuan/loveTech/wasm/emsdk/clang/fastcomp/build_incoming_64/bin
INFO:root:(Emscripten: Running sanity checks)

```

Thaks for your help😊.

By the way, how to know the toolchain and browser is matched?

**Comment by jfbastien** [comment]
Ha sorry! I misread the error message: your browser is the one that's too old compared to your toolchain. Emscripten 1.37.3 is the minimum you want. Try 1.37.2 with your browser, or try Nightly.

**Comment by Jiang-Xuan** [comment]
After I update Firefox Developer Edition version to ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:53.0) Gecko/20100101 Firefox/53.0`.Code was work well. Thanks again for your explain🍉.
