### ISSUE TITLE
Mutability flag missing on the binary encoding page

### ISSUE THREAD

**Issue by Bablakeluke** [WebAssembly/website#92]
`global_entry` defines a mutability flag which is mentioned but not displayed here:

http://webassembly.org/docs/binary-encoding/#global-entry

I believe the table should be like this instead:

| Field | Type | Description |
|---|---|---|
| flags | `varuint1` | mutability flag |
| type  | `global_type`  | type of the variables  |
| init | `init_expr`  | the initial value of the global  |

**Comment by s3ththompson** [comment]
Thanks for filing! I opened the issue on the design repo which is the markdown source for the website.
