### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by mseddon** [WebAssembly/website#94]
on `http://webassembly.org/docs/binary-encoding/`, in language types, for the definition of `elem_type` there is the following text:

A varint7 indicating the types of elements in a table. In the MVP, only one type is available:

The link to the table incorrectly points to `http://webassembly.org/docs/ast-semantics/#table`, but it should point to `http://webassembly.org/docs/semantics/#table`.

**Comment by s3ththompson** [comment]
Thanks! Fixed in https://github.com/WebAssembly/design/pull/1083
